name       : gegl3
version    : 0.3.14
release    : 21
source     :
    - https://download.gimp.org/pub/gegl/0.3/gegl-0.3.14.tar.bz2 : 09f5e2e6899697641d4660e3e274aed696f5bacc96ba389ac77674ee1156590a
license    :
    - GPL-3.0
    - LGPL-3.0
summary    : GEGL (Generic Graphics Library) is a graph based image processing framework.
component  : multimedia.graphics
builddeps  :
    - pkgconfig(babl)
    - pkgconfig(exiv2)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libavfilter)
    - pkgconfig(libpng15)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libv4l2)
    - pkgconfig(libwebp)
    - pkgconfig(pangocairo)
    - pkgconfig(sdl2)
    - jasper-devel
    - libjpeg-turbo-devel
    - vala
libsplit   : no
description: |
    GEGL provides infrastructure to do demand based cached non destructive image editing on larger than RAM buffers. Through babl it provides support for a wide range of color models and pixel storage formats for input and output.
setup      : |
    %configure --disable-static --with-vala
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/bin
