name       : gegl3
version    : 0.3.32
release    : 26
source     :
    - https://download.gimp.org/pub/gegl/0.3/gegl-0.3.32.tar.bz2 : a30e74ab2622b8c5e15c2a9ae27af72970bfa9380a67fde5211bf4bea7ade34d
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : multimedia.graphics
libsplit   : no
summary    : GEGL (Generic Graphics Library) is a graph based image processing framework.
description: |
    GEGL provides infrastructure to do demand based cached non destructive image editing on larger than RAM buffers. Through babl it provides support for a wide range of color models and pixel storage formats for input and output.
builddeps  :
    - pkgconfig(babl)
    - pkgconfig(exiv2)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(jasper)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libavfilter)
    - pkgconfig(libpng15)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libv4l2)
    - pkgconfig(libwebp)
    - pkgconfig(pangocairo)
    - pkgconfig(sdl2)
    - vala
setup      : |
    %configure --disable-static --with-vala
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/bin
